#! /usr/bin/env python3

import csv
import os
import re
import sys
import xlsxwriter

def usage(name, to=sys.stderr):
    print("""Usage: %s [-i input [worksheet-name]] -o output

Each input becomes a separate worksheet. "input" may be given as "-" for stdin.
(This is useful if you want to provide a worksheet name for the input from
stdin.) If no inputs are specified, stdin is assumed. If no name is given for
the worksheet, a default name is used.""" % name, file=to)

def exit_with_error(error, name):
    print("%s: %s!" % (name, error), file=sys.stderr)
    usage(name)
    sys.exit(1)

if __name__ == '__main__':
    name = os.path.basename(sys.argv[0])
    inputs = []
    output = None

    if len(sys.argv) == 0:
        usage(name, to=sys.stdout)
        sys.exit(0)

    mode = 'flag_search'
    for arg in sys.argv[1:]:
        if mode == 'maybe_name':
            mode = 'flag_search'
            if arg != '-o' and arg != '-i':
                inputs.append((last_input, arg))
                continue
            else:
                inputs.append((last_input, None))

        if mode == 'flag_search':
            if arg == '-o':
                mode = 'set_output'
            elif arg == '-i':
                mode = 'add_input'
            else:
                exit_with_error('Unrecognized flag "%s"' % arg, name)
        elif mode == 'set_output':
            output = arg
            mode = 'flag_search'
        elif mode == 'add_input':
            if arg == '-':
                last_input = sys.stdin
            else:
                last_input = open(arg)
            mode = 'maybe_name'

    if mode == 'maybe_name':
        inputs.append((last_input, None))

    if len(inputs) == 0:
        inputs.append((sys.stdin, None))

    if output is None:
        exit_with_error('No output provided', name);

    with xlsxwriter.Workbook(output) as workbook:
        for worksheet_input in inputs:
            worksheet = workbook.add_worksheet(worksheet_input[1])
            worksheet_reader = csv.reader(worksheet_input[0])

            row_index = 0
            for row in worksheet_reader:
                cell_index = 0
                for cell in row:
                    if re.match('^-?[0-9]+(.[0-9]+)?$', cell):
                        worksheet.write_number(row_index, cell_index, float(cell))
                    else:
                        worksheet.write(row_index, cell_index, cell)
                    cell_index += 1
                row_index += 1

            worksheet_input[0].close()
